---
- name: Check if the file exists
  stat:
    path: ~/.bash_profile 
  register: file_status

- name: Create Hidden Bash Profile In Home Directory If It Doesn't Exist
  file:
    path: ~/.bash_profile
    state: touch
    mode: '0644'
  when: not file_status.stat.exists

- name: Add ansible SSH key to ssh-agent
  tags: ssh_agent, ssh
  lineinfile:
    line: "eval $(ssh-agent) && ssh-add ~/.ssh/{{ env.ansible_key_name }}"
    path: ~/.bash_profile
  register: ssh_agent_setup

- name: Print results from setting up SSH agent
  tags: ssh_agent, ssh
  debug:
    var: ssh_agent_setup
